services:
  - type: web
    name: rithamtravels
    env: python
    plan: free

    runtime: python
    pythonVersion: "3.10.13"

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate

    startCommand: gunicorn ritham_tours.wsgi:application
