services:
  - type: web
    name: rithamtravels
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn ritham_tours.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ritham_tours.settings
      - key: PYTHON_VERSION
        value: 3.10.13
